# Generated by Django 4.2.13 on 2024-07-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Personal", "Personal"),
                            ("Work", "Work"),
                            ("Travel", "Travel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
