# Generated by Django 4.2.14 on 2024-07-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_journalentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='user',
        ),
    ]
